<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
	<TargetFramework>net10.0-windows10.0.26100.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <IsPackable>false</IsPackable>
    <AllowUnsafeBlocks>true</AllowUnsafeBlocks>
    <Platforms>AnyCPU;x64</Platforms>
	<RuntimeIdentifier>win-x64</RuntimeIdentifier>
  </PropertyGroup>

  <ItemGroup>
    <Compile Remove="Application\**" />
    <Compile Remove="Unit_Test_Moq_Logic\**" />
    <Content Remove="Application\**" />
    <Content Remove="Unit_Test_Moq_Logic\**" />
    <EmbeddedResource Remove="Application\**" />
    <EmbeddedResource Remove="Unit_Test_Moq_Logic\**" />
    <None Remove="Application\**" />
    <None Remove="Unit_Test_Moq_Logic\**" />
    <Page Remove="Application\**" />
    <Page Remove="Unit_Test_Moq_Logic\**" />
    <PRIResource Remove="Application\**" />
    <PRIResource Remove="Unit_Test_Moq_Logic\**" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="coverlet.collector" Version="10.0.0">
      <PrivateAssets>all</PrivateAssets>
      <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
    </PackageReference>
    <PackageReference Include="Microsoft.Extensions.TimeProvider.Testing" Version="10.5.0" />
    <PackageReference Include="Microsoft.NET.Test.Sdk" Version="18.5.1" />
    <PackageReference Include="Moq" Version="4.20.72" />
    <PackageReference Include="OpenTelemetry.Api" Version="1.15.3" />
    <PackageReference Include="OpenTelemetry.Exporter.OpenTelemetryProtocol" Version="1.15.3" />
    <PackageReference Include="Shouldly" Version="4.3.0" />
    <PackageReference Include="WireMock.Net" Version="2.6.0" />
    <PackageReference Include="xunit" Version="2.9.3" />
    <PackageReference Include="xunit.runner.visualstudio" Version="3.1.5">
      <PrivateAssets>all</PrivateAssets>
      <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
    </PackageReference>
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\eBRestarter.Infrastructure\eBRestarter.Infrastructure.csproj" />
  </ItemGroup>

  <ItemGroup>
    <Using Include="Xunit" />
  </ItemGroup>

</Project>